In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
clf = RandomForestClassifier(random_state=42)
X = [[1, 2, 3],
     [11, 12, 13]]
y = [0, 1]
clf.fit(X, y)


RandomForestClassifier(random_state=42)

In [7]:
clf.predict(X)

array([0, 1])

In [8]:
clf.predict([[4, 5, 6], [14, 15, 16]])

array([0, 1])

In [14]:
from sklearn.preprocessing import StandardScaler
X = np.random.randint(-10, 100, size=(10,3))
StandardScaler().fit(X).transform(X)

array([[-0.53896081,  0.0580162 , -0.54308573],
       [ 1.40728655,  0.5326942 , -1.34537146],
       [-0.50901854, -0.5748878 , -0.69737145],
       [ 2.06601643,  0.5326942 ,  0.84548574],
       [-0.65872988, -2.20988979,  1.37005718],
       [-0.50901854,  0.6909202 ,  1.40091432],
       [-0.83838348, -0.0474678 ,  0.01234286],
       [-0.53896081, -1.1023078 ,  0.93805717],
       [ 0.92821028,  1.4293082 , -1.06765717],
       [-0.80844121,  0.6909202 , -0.91337145]])

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    LogisticRegression()
)

# Split the data into train and test
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Fit the whole pipeline
pipe.fit(X_train, y_train)

# Assess performance
accuracy_score(pipe.predict(X_test), y_test)


0.9736842105263158

In [ ]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

# Simulate data
X, y = make_regression(n_samples = 1000, random_state=42)

# Set up linear model object
lr = LinearRegression()

# Conduct cross validation, which includes model fitting
result = cross_validate(lr, X, y)

# Examine test_score
result['test_score']

array([1., 1., 1., 1., 1.])

In [22]:
result

{'fit_time': array([0.02037621, 0.01321006, 0.01285625, 0.01176381, 0.01265311]),
 'score_time': array([0.00057793, 0.00056982, 0.00050879, 0.00051284, 0.00066614]),
 'test_score': array([1., 1., 1., 1., 1.])}

In [ ]:
from sklearn.datasets import make_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import randint

# Create a synthetic dataset
X, y = make_regression(n_samples=20640,
                       n_features=8,
                       noise=0.1,
                       random_state=42)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Define the hyperparameter space
param_distributions = {'n_estimators': randint(1, 5),
                       'max_depth': randint(5, 10)}

# Create a RandomSearchCV object and fit with data
search = RandomizedSearchCV(estimator=RandomForestRegressor(random_state=42),
                        n_iter=5,
                        param_distributions=param_distributions,
                        random_state=42)
search.fit(X_train, y_train)

# Get best hyperparameters
search.best_params_
# {'max_depth': 7, 'n_estimators': 4}

# search object can then be used in making predictions
search.score(X_test, y_test)
# 0.7925192997818057


0.7925192997818057

In [27]:
import pandas as pd
adult_census = pd.read_csv("../datasets/adult-census.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../datasets/adult-census.csv'